name: Check Markdown links

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: gaurav-nelson/github-action-markdown-link-check@1.0.12
